name: Build and Release JAR

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build JAR
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/*.jar

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: target

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          files: target/*.jar
          draft: false
          prerelease: false

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
