name: Build and Release JAR

on:
  release:
    types:
      - created

jobs:
  publish:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Get the upload URL for a release
      id: get
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug
      run: echo "$(ls -1)"

    - name: Upload Release Asset fat jar
      id: upload-release-asset-fat 
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get.outputs.upload_url }} 
        asset_path: target/*.jar
        asset_name: quiz-app.jar
        asset_content_type: application/java-archive
            
